version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: auto
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "security"
    reviewers: []
    versioning-strategy: increase
    registries: []
    groups:
      security:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"